apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkyNDQ2NjQuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImJHRnJhMkZ0Y21GcWRUcFRVR1JoY214cGJtY3hNak5BIgoJCX0KCX0KfQ
type: kubernetes.io/dockerconfigjson